# Cross-Method Analysis Mode Configuration
# For analyzing pre-computed results from different methods

defaults:
  - ../unified_evaluation

# Override mode
mode: "cross_method_analysis"

# Cross-method analysis specific settings
experiment:
  name: "cross_method_analysis"
  output_dir: "outputs/cross_method_analysis"

processing:
  max_images: null  # Analyze all available results
  save_individual_comparisons: true
  save_summary_plots: true
  significance_level: 0.05

# Comprehensive metrics for publication-ready analysis
metrics:
  image_quality: ["psnr", "ssim", "frc", "mse", "mae", "snr"]
  perceptual: ["sar", "sharpness", "contrast", "entropy", "spectral_angle"]
  downstream: ["cellpose_f1", "hausdorff_distance", "dice_coefficient", "iou"]
  robustness: ["noise_robustness", "hallucination_score"]

# Cross-analysis paths - UPDATE THESE WITH YOUR ACTUAL PATHS
cross_analysis:
  pkl_dir: "outputs/pkl_results"
  l2_dir: "outputs/l2_results" 
  anscombe_dir: "outputs/anscombe_results"
  rl_dir: "outputs/richardson_lucy_results"
  rcan_dir: "outputs/rcan_results"

# Input and GT still needed for metric computation
inference:
  input_dir: "data/test/wf"
  gt_dir: "data/test/2p"
  output_dir: "outputs/cross_method_analysis"

wandb:
  tags: 
    - "cross_method_analysis"
    - "publication_ready"
    - "comprehensive_metrics"
  job_type: "cross_method_analysis"
