# Full FOV Evaluation Mode Configuration
# For large image evaluation with patch-based processing

defaults:
  - ../unified_evaluation

# Override mode
mode: "full_fov"

# Full FOV specific settings
experiment:
  name: "full_fov_evaluation"
  output_dir: "outputs/full_fov_evaluation"

# Patch processing configuration
processing:
  patch_size: 256
  stride: 128
  feather_size: 64  # Half of stride for smooth blending
  max_images: 5  # Limit for large images
  save_individual_comparisons: true
  save_summary_plots: true

# Focus on key metrics for patch processing
metrics:
  image_quality: ["psnr", "ssim", "frc"]
  perceptual: ["sar", "sharpness", "contrast"]
  downstream: []  # Skip downstream for patch processing
  robustness: ["noise_robustness"]

# Enable baselines for comparison
baselines:
  use_richardson_lucy: true
  use_rcan: true  # Set to false if no RCAN checkpoint

wandb:
  tags: 
    - "full_fov_evaluation"
    - "patch_processing"
  job_type: "full_fov_evaluation"
