# UNet model configuration for diffusion training
sample_size: 256
in_channels: 1  # unconditional prior by default; conditioner concatenation optional
out_channels: 1
layers_per_block: 2
block_out_channels: [64, 128, 256, 512]
down_block_types: ["DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D"]
class_embed_type: null
cross_attention_dim: null

